### ISSUE TITLE
Bug: CompositeBezierCurve constructor from control points

### ISSUE THREAD

**Issue by WenchaoDing** [barkm/bezier#1]
Hi,

Thanks for your contribution. It is a really cool and convenient library!

I find a tiny bug for the constructor of CompositeBezierCurve (only for constructor from control points)

`        for(int i = 1; i < _bezier_curves.size(); i++){ `
            `if(_bezier_curves[i-1](0) != _bezier_curves[i](0)){`

where the first check should be 
`_bezier_curves[i-1](1) != _bezier_curves[i](0)`

**Comment by barkm** [comment]
Hi, thank you for reporting the bug. If you encounter more bugs, please report them as well. I'm glad you like the library - hope you'll find it useful!
