### ISSUE TITLE
References for least square bezier fitting?

### ISSUE THREAD

**Issue by anthrotype** [barkm/bezier#2]
Hi, I've only skimmed through briefly and this looks very cool. I was wondering if you could point me to the reaearch papers or books that you used as references for implementing this particular bezier fitting algorithm? 
Thank you

**Comment by barkm** [comment]
Hi - thanks for showing interest! Sorry for this late reply. 

The curve fitting algorithm was derived without any particular reference, so unfortunately I don't have any pointers to papers or books to share. I might add details on the algorithm at some point!
